version: "3.9"
services:
  web:
    container_name: webbase-web
    ports:
      - "80:80"
    volumes:
    - .:/application:rw
    - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    build:
      context: './docker/nginx/'
    links:
      - db
      - php
  db:
    container_name: webbase-db
    image: mariadb:latest
    ports:
      -  '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=webbasedb"
      - "MYSQL_DATABASE=webbase"
  php:
    container_name: webbase-php
    volumes:
      - .:/application:rw
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    build:
      context: './docker/php/'
    links:
      - db
      - cache
  cache:
    container_name: webbase-redis
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass webbase-redis
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local