<?php

return [
  "title" => "Account",
  "login_title" => "Einloggen",
  "login_description" => "Loggen Sie sich in Ihren Account ein",
  "accept_invite_title" => "Einladung",
  "accept_invite_description" => "Schließen Sie die Registrierung ab indem Sie ein Passwort wählen",
  "confirm_email_title" => "E-Mail Adresse bestätigen",
  "confirm_email_description" => "Schließen Sie die Registrierung ab indem Sie Ihre E-Mail Adresse bestätigen",
  "registration_title" => "Registration",
  "registration_description" => "Erstelle einen neuen Account",
  "resend_confirm_email_title" => "Bestätigungsmail erneut senden",
  "resend_confirm_email_description" => "Eine neue Bestätigungsmail anfordern um die Accounterstellung abzuschließen",
  "resend_confirm_email_form_title" => "Geben Sie Ihre E-Mailadresse ein, um eine neue Bestätigungsmail zu erhalten",
  "reset_password_title" => "Password zurücksetzen",
  "reset_password_description" => "Fordern Sie ein Passwort-Reset an, sobald Sie eine E-Mail erhalten, können Sie ein neues Passwort wählen",
  "reset_password_form_title" => "Ein neues Passwort wählen",
  "reset_password_request_form_title" => "Geben Sie Ihre E-Mail Adresse ein um ein Passwort-Reset Token zu erhalten",
  "form_title" => "Bitte geben Sie ihre Daten ein",
  "username" => "Benutzername",
  "username_or_email" => "Benutzername oder E-Mail",
  "email" => "E-Mail Adresse",
  "password" => "Passwort",
  "password_confirm" => "Passwort bestätigen",
  "remember_me" => "Eingeloggt bleiben",
  "signing_in" => "Einloggen",
  "sign_in" => "Einloggen",
  "forgot_password" => "Passwort vergessen?",
  "passwords_do_not_match" => "Die Passwörter stimmen nicht überein",
  "back_to_login" => "Zurück zum Login",
  "register_text" => "Noch keinen Account? Jetzt registrieren",
  "6_digit_code" => "6-stelliger Code",
  "2fa_title" => "Es werden weitere Informationen zum Einloggen benötigt",
  "2fa_text" => "Stecke dein 2FA-Gerät ein. Möglicherweise wird noch eine Interaktion benötigt, z.B. durch Eingabe einer PIN oder durch Berühren des Geräts",
  "confirming_email" => "Bestätige E-Mail Adresse",
  "proceed_to_login" => "Weiter zum Login",
  "invalid_link" => "Den Link den Sie besucht haben ist nicht länger gültig",
  "confirm_success" => "Ihre E-Mail Adresse wurde erfolgreich bestätigt, Sie können sich jetzt einloggen",
  "confirm_error" => "Fehler beim Bestätigen der E-Mail Adresse",
];