<?php

return [
  "title" => "Account",
  "users" => "Benutzer",
  "login_title" => "Einloggen",
  "login_description" => "Loggen Sie sich in Ihren Account ein",
  "accept_invite_title" => "Einladung",
  "accept_invite_description" => "Schließen Sie die Registrierung ab indem Sie ein Passwort wählen",
  "confirm_email_title" => "E-Mail Adresse bestätigen",
  "confirm_email_description" => "Schließen Sie die Registrierung ab indem Sie Ihre E-Mail Adresse bestätigen",
  "confirm_gpg_title" => "GPG-Schlüssel bestätigen",
  "confirm_gpg_error" => "Fehler beim Bestätigen des GPG-Schlüssels",
  "confirm_gpg_success" => "GPG-Schlüssel erfolgreich bestätigt",
  "registration_title" => "Registration",
  "registration_description" => "Erstelle einen neuen Account",
  "resend_confirm_email_title" => "Bestätigungsmail erneut senden",
  "resend_confirm_email_description" => "Eine neue Bestätigungsmail anfordern um die Accounterstellung abzuschließen",
  "resend_confirm_email_form_title" => "Geben Sie Ihre E-Mailadresse ein, um eine neue Bestätigungsmail zu erhalten",
  "reset_password_title" => "Passwort zurücksetzen",
  "reset_password_description" => "Fordern Sie ein Passwort-Reset an, sobald Sie eine E-Mail erhalten, können Sie ein neues Passwort wählen",
  "reset_password_form_title" => "Ein neues Passwort wählen",
  "reset_password_request_form_title" => "Geben Sie Ihre E-Mail Adresse ein um ein Passwort-Reset Token zu erhalten",
  "form_title" => "Bitte geben Sie ihre Daten ein",
  "name" => "Name",
  "username" => "Benutzername",
  "username_or_email" => "Benutzername oder E-Mail",
  "email" => "E-Mail Adresse",
  "password" => "Passwort",
  "password_confirm" => "Passwort bestätigen",
  "password_old" => "Altes Passwort",
  "password_new" => "Neues Passwort",
  "full_name" => "Voller Name",
  "remember_me" => "Eingeloggt bleiben",
  "signing_in" => "Einloggen",
  "sign_in" => "Einloggen",
  "confirmed" => "Bestätigt",
  "forgot_password" => "Passwort vergessen?",
  "change_password" => "Passwort ändern",
  "passwords_do_not_match" => "Die Passwörter stimmen nicht überein",
  "back_to_login" => "Zurück zum Login",
  "register_text" => "Noch keinen Account? Jetzt registrieren",
  "6_digit_code" => "6-stelliger Code",
  "2fa_title" => "Es werden weitere Informationen zum Einloggen benötigt",
  "2fa_text" => "Stecke dein 2FA-Gerät ein. Möglicherweise wird noch eine Interaktion benötigt, z.B. durch Eingabe einer PIN oder durch Berühren des Geräts",
  "confirming_email" => "Bestätige E-Mail Adresse",
  "proceed_to_login" => "Weiter zum Login",
  "invalid_link" => "Den Link den Sie besucht haben ist nicht länger gültig",
  "confirm_success" => "Ihre E-Mail Adresse wurde erfolgreich bestätigt, Sie können sich jetzt einloggen",
  "confirm_error" => "Fehler beim Bestätigen der E-Mail Adresse",
  "gpg_key" => "GPG-Schlüssel",
  "no_gpg_key_added" => "Kein GPG-Schlüssel hinzugefügt",
  "download_gpg_key" => "GPG-Schlüssel herunterladen",
  "2fa_token" => "Zwei-Faktor Authentifizierung (2FA)",
  "profile_picture_of" => "Profilbild von",
  "profile_of" => "Profil von",
  "language" => "Sprache",
  "profile" => "Benutzerprofil",
  "loading_profile" => "Lade Benutzerprofil",
  "error_profile_get" => "Fehler beim Laden des Benutzerprofils",
  "registered_at" => "Registriert am",
  "last_online" => "Zuletzt online",
  "groups" => "Gruppen",
  "group_name" => "Gruppenname",
  "new_group" => "Neue Gruppe",
  "members" => "Mitglieder",
  "member_count" => "Mitgliederanzahl",
  "color" => "Farbe",
  "logged_in_as" => "Eingeloggt als",
  "active" => "Aktiv",
  "group" => "Gruppe",
  "no_members" => "Keine Mitglieder in dieser Gruppe",

  # dialogs
  "fetch_group_members_error" => "Fehler beim Holen der Gruppenmitglieder",
  "remove_group_member_error" => "Fehler beim Entfernen des Gruppenmitglieds",
  "add_group_member_error" => "Fehler beim Hinzufügen des Gruppenmitglieds",
  "create_group_error" => "Fehler beim Erstellen der Gruppe",
  "update_group_error" => "Error beim Aktualisieren der Gruppe",
  "delete_group_error" => "Error beim Löschen der Gruppe",
  "search_users_error" => "Fehler beim Suchen des Benutzers",
  "delete_group_title" => "Gruppe löschen",
  "delete_group_text" => "Möchten Sie diese Gruppe wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
  "remove_group_member_title" => "Mitglied entfernen",
  "remove_group_member_text" => "Möchten Sie wirklich den Benutzer '%s' von dieser Gruppe entfernen?",
  "add_group_member_title" => "Mitglied hinzufügen",
  "add_group_member_text" => "Einen Benutzer suchen um ihn der Gruppe hinzuzufügen",

  # GPG Key
  "gpg_key_placeholder_text" => "GPG-Key im ASCII format reinziehen oder einfügen...",

  # 2fa
  "register_2fa_device" => "Ein 2FA-Gerät registrieren",
  "register_2fa_totp_text" => "Scan den QR-Code mit einem Gerät, das du als Zwei-Faktor-Authentifizierung (2FA) benutzen willst. " .
    "Unter Android kannst du den Google Authenticator benutzen.",
  "register_2fa_fido_text" => "Möglicherweise musst du mit dem Gerät interagieren, zum Beispiel durch Eingeben einer PIN oder durch Berühren des Geräts",
  "remove_2fa" => "2FA-Token entfernen",
  "remove_2fa_text" => "Gib dein aktuelles Passwort ein um das Entfernen des 2FA-Tokens zu bestätigen",
];