<?php

return [
  "something_went_wrong" => "Etwas ist schief gelaufen",
  "error_occurred" => "Ein Fehler ist aufgetreten",
  "retry" => "Erneut versuchen",
  "go_back" => "Zurück",
  "save" => "Speichern",
  "save_only" => "Nur Speichern",
  "saved" => "Gespeichert",
  "saving" => "Speichere",
  "unsaved_changes" => "Du hast nicht gespeicherte Änderungen",
  "new" => "Neu",
  "edit" => "Bearbeiten",
  "apply" => "Übernehmen",
  "submitting" => "Übermittle",
  "submit" => "Absenden",
  "request" => "Anfordern",
  "cancel" => "Abbrechen",
  "confirm" => "Bestätigen",
  "add" => "Hinzufügen",
  "ok" => "OK",
  "id" => "ID",
  "user" => "Benutzer",
  "language" => "Sprache",
  "loading" => "Laden",
  "logout" => "Ausloggen",
  "noscript" => "Sie müssen Javascript aktivieren um diese Anwendung zu benutzen",
  "name" => "Name",
  "type" => "Typ",
  "size" => "Größe",
  "not_supported" => "Nicht unterstützt",
  "yes" => "Ja",
  "no" => "Nein",

  # dialog / actions
  "action" => "Aktion",
  "actions" => "Aktionen",
  "title" => "Titel",
  "message" => "Nachricht",
  "rename" => "Umbenennen",
  "remove" => "Entfernen",
  "change" => "Bearbeiten",
  "close" => "Schließen",
  "reset" => "Zurücksetzen",
  "move" => "Verschieben",
  "delete" => "Löschen",
  "info" => "Info",
  "reload" => "Aktualisieren",
  "success" => "Erfolg",

  # file
  "choose_file" => "Datei auswählen",
  "download" => "Herunterladen",
  "download_all" => "Alles Herunterladen",
  "upload" => "Hochladen",
  "uploading" => "Lade hoch",
  "overwrite" => "Überschreiben",

  # data table
  "showing_x_of_y_entries" => "Zeige %d von %d Einträgen",
  "controls" => "Steuerung",

  # date / time
  "date" => "Datum",
  "start_date" => "Startdatum",
  "end_date" => "Enddatum",
  "last_modified" => "Zuletzt geändert",
  "timestamp" => "Zeitpunkt",
  "date_format" => "d.m.Y",
  "date_time_format" => "d.m.Y H:i",
  "date_time_format_precise" => "d.m.Y H:i:s",
  "time_format" => "H:i",
  "time_format_precise" => "H:i:s",
  "datefns_date_format" => "dd.MM.yyyy",
  "datefns_time_format" => "HH:mm",
  "datefns_time_format_precise" => "HH:mm:ss",
  "datefns_datetime_format" => "dd.MM.yyyy HH:mm",
  "datefns_datetime_format_precise" => "dd.MM.yyyy HH:mm:ss",
];