<?php

return [
  "title" => "Account",
  "users" => "Users",
  "login_title" => "Sign In",
  "login_description" => "Sign In into your account",
  "accept_invite_title" => "Invitation",
  "accept_invite_description" => "Complete your account registration by choosing a password",
  "confirm_email_title" => "Confirm Email",
  "confirm_email_description" => "Complete your registration by confirming the e-mail address",
  "confirm_gpg_title" => "Confirm GPG Key",
  "confirm_gpg_error" => "Error confirming GPG Key",
  "confirm_gpg_success" => "Successfully confirmed GPG Key",
  "registration_title" => "Registration",
  "registration_description" => "Create a new account",
  "resend_confirm_email_title" => "Resend Confirm Email",
  "resend_confirm_email_description" => "Request a new confirmation email to finalize the account creation",
  "resend_confirm_email_form_title" => "Enter your E-Mail address, to receive a new e-mail to confirm your registration.",
  "reset_password_title" => "Reset Password",
  "reset_password_description" => "Request a password reset, once you got the e-mail address, you can choose a new password",
  "reset_password_form_title" => "Choose a new password",
  "reset_password_request_form_title" => "Enter your E-Mail address, to receive a password reset token.",
  "form_title" => "Please fill with your details",
  "name" => "Name",
  "username" => "Username",
  "username_or_email" => "Username or E-Mail",
  "email" => "E-Mail Address",
  "full_name" => "Full Name",
  "remember_me" => "Remember Me",
  "signing_in" => "Signing in",
  "sign_in" => "Sign In",
  "confirmed" => "Confirmed",
  "register_text" => "Don't have an account? Sign Up",
  "passwords_do_not_match" => "Your passwords did not match",
  "back_to_login" => "Back to Login",
  "confirming_email" => "Confirming email",
  "proceed_to_login" => "Proceed to Login",
  "invalid_link" => "The link you visited is no longer valid",
  "confirm_success" => "Your e-mail address was successfully confirmed, you may now log in",
  "confirm_error" => "Error confirming e-mail address",
  "profile_of" => "Profile of",
  "language" => "Language",
  "profile" => "User Profile",
  "loading_profile" => "Loading Profile",
  "error_profile_get" => "Error retrieving user profile",
  "registered_at" => "Registered At",
  "last_online" => "Last Online",
  "groups" => "Groups",
  "group_name" => "Group Name",
  "new_group" => "New Group",
  "members" => "Members",
  "member_count" => "Member Count",
  "color" => "Color",
  "logged_in_as" => "Logged in as",
  "active" => "Active",
  "group" => "Group",
  "no_members" => "No members in this group",
  "edit_profile" => "Edit Profile",
  "user_list_placeholder" => "No users to display",

  # user edit page
  "edit_user" => "Edit User",
  "new_user" => "New User",
  "send_invite" => "Send Invitation",
  "get_user_error" => "Error fetching user",
  "invite_user_error" => "Error sending invitation",
  "create_user_error" => "Error creating user",
  "save_user_error" => "Error saving user",

  # profile picture
  "remove_picture" => "Remove profile picture",
  "remove_picture_text" => "Do you really want to remove your current profile picture?",
  "change_picture" => "Change profile picture",
  "profile_picture_of" => "Profile Picture of",
  "change_picture_title" => "Change Profile picture",
  "change_picture_text" => "Choose a profile picture and adjust the visible area.",
  "profile_picture_invalid_dimensions" => "The profile picture must have at least a size of 150x150.",

  # dialogs
  "fetch_group_members_error" => "Error fetching group members",
  "remove_group_member_error" => "Error removing group member",
  "add_group_member_error" => "Error adding member",
  "create_group_error" => "Error creating group",
  "update_group_error" => "Error updating group",
  "delete_group_error" => "Error deleting group",
  "search_users_error" => "Error searching users",
  "search_groups_error" => "Error searching groups",
  "delete_group_title" => "Delete Group",
  "delete_group_text" => "Do you really want to delete this group? This action cannot be undone.",
  "remove_group_member_title" => "Remove member",
  "remove_group_member_text" => "Do you really want to remove user '%s' from this group?",
  "add_group_member_title" => "Add member",
  "add_group_member_text" => "Search a user to add to the group",
  "delete_user_error" => "Error deleting User",
  "delete_user_title" => "Delete User",
  "delete_user_text" => "Are you really sure you want to delete this user? This cannot be undone!",
  "error_reading_file" => "Error reading file",
  "invalid_gpg_key" => "Selected file is a not a GPG Public Key in ASCII format",

  # GPG Key
  "gpg_key" => "GPG Key",
  "no_gpg_key_added" => "No GPG key added",
  "download_gpg_key" => "Download GPG Key",
  "gpg_key_placeholder_text" => "Paste or drag'n'drop your GPG-Key in ASCII format...",

  # 2fa
  "2fa_title" => "Additional information is required for logging in",
  "2fa_text" => "Plugin your 2FA-Device. Interaction might be required, e.g. typing in a PIN or touching it.",
  "2fa_token" => "Two-Factor Authentication (2FA)",
  "2fa_type_totp" => "Time-Based 2FA (TOTP)",
  "2fa_type_fido" => "Key-Based 2FA",
  "register_2fa_device" => "Register a 2FA-Device",
  "register_2fa_totp_text" => "Scan the QR-Code with a device you want to use for Two-Factor-Authentication (2FA). " .
    "On Android, you can use the Google Authenticator.",
  "register_2fa_fido_text" => "You may need to interact with your Device, e.g. typing in your PIN or touching to confirm the registration.",
  "remove_2fa" => "Remove 2FA Token",
  "remove_2fa_text" => "Enter your current password to confirm the removal of your 2FA Token",
  "6_digit_code" => "6-Digit Code",

  # password
  "password" => "Password",
  "password_confirm" => "Confirm Password",
  "password_old" => "Old Password",
  "password_new" => "New Password",
  "forgot_password" => "Forgot password?",
  "change_password" => "Change password",
  "password_very_strong" => "Very strong",
  "password_strong" => "Strong",
  "password_ok" => "OK",
  "password_weak" => "Weak",
  "password_very_weak" => "Very weak",
];