<?php

return [
  "title" => "Account",
  "login_title" => "Sign In",
  "login_description" => "Sign In into your account",
  "accept_invite_title" => "Invitation",
  "accept_invite_description" => "Complete your account registration by choosing a password",
  "confirm_email_title" => "Confirm Email",
  "confirm_email_description" => "Complete your registration by confirming the e-mail address",
  "registration_title" => "Registration",
  "registration_description" => "Create a new account",
  "resend_confirm_email_title" => "Resend Confirm Email",
  "resend_confirm_email_description" => "Request a new confirmation email to finalize the account creation",
  "resend_confirm_email_form_title" => "Enter your E-Mail address, to receive a new e-mail to confirm your registration.",
  "reset_password_title" => "Reset Password",
  "reset_password_description" => "Request a password reset, once you got the e-mail address, you can choose a new password",
  "reset_password_form_title" => "Choose a new password",
  "reset_password_request_form_title" => "Enter your E-Mail address, to receive a password reset token.",
  "form_title" => "Please fill with your details",
  "username" => "Username",
  "username_or_email" => "Username or E-Mail",
  "email" => "E-Mail Address",
  "password" => "Password",
  "password_confirm" => "Confirm Password",
  "remember_me" => "Remember Me",
  "signing_in" => "Signing in",
  "sign_in" => "Sign In",
  "forgot_password" => "Forgot password?",
  "register_text" => "Don't have an account? Sign Up",
  "passwords_do_not_match" => "Your passwords did not match",
  "back_to_login" => "Back to Login",
  "6_digit_code" => "6-Digit Code",
  "2fa_title" => "Additional information is required for logging in",
  "2fa_text" => "Plugin your 2FA-Device. Interaction might be required, e.g. typing in a PIN or touching it.",
  "confirming_email" => "Confirming email",
  "proceed_to_login" => "Proceed to Login",
  "invalid_link" => "The link you visited is no longer valid",
  "confirm_success" => "Your e-mail address was successfully confirmed, you may now log in",
  "confirm_error" => "Error confirming e-mail address",
];