<?php

return [
  "something_went_wrong" => "Something went wrong",
  "error_occurred" => "An error occurred",
  "unsaved_changes" => "You have unsaved changed",
  "new" => "New",
  "language" => "Language",
  "loading" => "Loading",
  "logout" => "Logout",
  "noscript" => "You need Javascript enabled to run this app",
  "name" => "Name",
  "type" => "Type",
  "size" => "Size",
  "not_supported" => "Not supported",
  "yes" => "Yes",
  "no" => "No",

  # dialog / actions
  "action" => "Action",
  "actions" => "Actions",
  "title" => "Title",
  "message" => "Message",
  "edit" => "Edit",
  "submitting" => "Submitting",
  "submit" => "Submit",
  "request" => "Request",
  "cancel" => "Cancel",
  "confirm" => "Confirm",
  "ok" => "OK",
  "remove" => "Remove",
  "change" => "Change",
  "reset" => "Reset",
  "retry" => "Retry",
  "go_back" => "Go Back",
  "save" => "Save",
  "saving" => "Saving",
  "delete" => "Delete",
  "info" => "Info",
  "reload" => "Reload",
  "success" => "Success",

  # file
  "choose_file" => "Choose File",
  "download" => "Download",
  "download_all" => "Download All",
  "upload" => "Upload",
  "uploading" => "Uploading",
  "rename" => "Rename",
  "move" => "Move",
  "overwrite" => "Overwrite",


  # data table
  "showing_x_of_y_entries" => "Showing %d of %d entries",
  "controls" => "Controls",

  # date / time
  "date" => "Date",
  "start_date" => "Start Date",
  "end_date" => "End Date",
  "last_modified" => "Last Modified",
  "timestamp" => "Timestamp",
  "date_format" => "m/d/Y",
  "date_time_format" => "m/d/Y G:i A",
  "date_time_format_precise" => "m/d/Y G:i:s A",
  "time_format" => "G:i A",
  "time_format_precise" => "G:i:s A",
  "datefns_date_format" => "MM/dd/yyyy",
  "datefns_time_format" => "p",
  "datefns_time_format_precise" => "pp",
  "datefns_datetime_format" => "MM/dd/yyyy p",
  "datefns_datetime_format_precise" => "MM/dd/yyyy pp",
];